export default{
    EN: {
        HeaderText:"Guess a Number",
        StartGameHeaderText: "Start a New Game",
        UserChoiceInputText: "Select a Number",
        ResetButtonText: "Reset",
        ConfirmButtonText: "Confirm",
        StartGameButtonText: "Start Game",
        SelectedNumberHelpText:"You have selected",
        OpponentGuessHelpText: "Opponent's Guess",
        LowerButtonText: "Lower",
        GreaterButtonText: "Greater",
        GameOverHeaderText: "Game Over !!!",
        NumberOfRoundsHelpText:"Number of Rounds",
        StartNewGameButtonText: "New Game",
        InvalidNumberAlertTitle: "Invalid Number!", 
        InvalidNumberErrorDescription: "Enter a valid number between 1 and 99.",
        OkayButtonText: "Okay",
        FalseButtonAlertTitle:'Don\'t Lie!', 
        FalseButtonAlertDescription: "You know that",
        SorryButtonText: "Sorry!"
    },
    TL: {
        HeaderText:"సంఖ్య ను ఊహించండి",
        StartGameHeaderText: "కొత్త ఆట ప్రారంభించు",
        UserChoiceInputText: "సంఖ్య ను ఎంచుకో",
        ResetButtonText: "రద్దు చేయి",
        ConfirmButtonText: "ఎంచుకో",
        StartGameButtonText: "ఆట ప్రారంభించు",
        SelectedNumberHelpText:"మీరు ఎంచుకున్న సంఖ్య",
        OpponentGuessHelpText: "ప్రత్యర్థి ఊహించిన సంఖ్య",
        LowerButtonText: "చిన్నది",
        GreaterButtonText: "పెద్దది",  
        GameOverHeaderText: "ఆట ముగిసింది !!!",
        NumberOfRoundsHelpText:"మొత్తం రౌండ్లు",
        StartNewGameButtonText: "కొత్త ఆట",
        InvalidNumberAlertTitle: "ఈ సంఖ్య  చెల్లదు!", 
        InvalidNumberErrorDescription: "మీరు ఎంచుకునే సంఖ్య  1 నుండి 99 మధ్యలోనే ఉండాలి.",
        OkayButtonText: "సరే",
        FalseButtonAlertTitle:'ఇది నిజం కాదు!', 
        FalseButtonAlertDescription: "అది మీకు కూడా తెలుసు",
        SorryButtonText: "క్షమించు!"        
    }
}